In [ ]:
import random
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt

In [ ]:
Applicant_ID = np.arange(1, 3001)

school_names = pd.read_csv('school_names.csv')
school_list = school_names['name']
School_Name = np.random.choice(school_list, 3000, replace=True)

GPA = np.random.uniform(0.00, 5.00, size=3000)
GPA = np.round(GPA,2)

degree_list = ["Bachelors", "Masters", "Phd"]
Degree = np.random.choice(degree_list, 3000, replace=True)

locations = pd.read_csv('locations.csv')
location_list = locations['location']
Location = np.random.choice(location_list, 3000, replace=True)

gender_list = ["M", "F", "N/A"]
Gender = np.random.choice(gender_list, 3000, replace=True)

vs_list = [1, 0, "N/A"]
Veteran_status = np.random.choice(vs_list, 3000, replace=True)

wa_list = [1, 0]
Work_authorization = np.random.choice(wa_list, 3000, replace=True)

disability_list = [1, 0, "N/A"]
Disability = np.random.choice(disability_list, 3000, replace=True)

ethnicity_list = [0, 1, 2, 3, 4]
Ethnicity = np.random.choice(ethnicity_list, 3000, replace=True)

# Resume_score = np.random.uniform(0.00, 10.00, size=3000)
# Resume_score = np.round(GPA,2)

In [ ]:
role_df = pd.read_csv('roles.csv')
role_list = role_df['Job Roles']
Role1 = np.random.choice(role_list, 3000, replace=True)
# randomly choose some values in Role 1 to be nan
empty_idx = sorted(np.random.choice(3000, 500, replace=False))
Role1[empty_idx] = "N/A"

start_date = datetime(2002, 1, 1)
end_date = datetime(2024, 12, 31)
Start1 = []
End1 = []
# randomly choose some dates in End 1 to be nan
Role1_not_empty = np.setdiff1d(np.arange(3000), empty_idx)
empty_idx1 = np.random.choice(Role1_not_empty, size=500, replace=False)
for i in range(3000):
  if i in empty_idx:
    Start1.append("N/A")
    End1.append("N/A")
  else:
    random_start = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    Start1.append(random_start.strftime("%m/%y"))
    if i in empty_idx1:
      End1.append("N/A")
    else:
      random_end = random_start + timedelta(days=random.randint(0, (end_date - random_start).days))
      End1.append(random_end.strftime("%m/%y"))
Start1 = np.array(Start1)
End1 = np.array(End1)

# assign roles to Role 2 and make sure values are nan where Role 1 is nan
Role2 = np.random.choice(role_list, 3000, replace=True)
Role2[empty_idx] = "N/A"
# randomly choose some roles in Role 2 to be nan
Role2_not_empty = np.where(Role2 != "N/A")[0]
empty_idx2 = np.random.choice(Role2_not_empty, size=500, replace=False)
Role2[empty_idx2] = "N/A"
# assign dates to where Role 2 is not nan
Role2_not_nan = np.where(Role2 != "N/A")[0]
Start2 = []
End2 = []
for i in range(3000):
  if i in Role2_not_nan:
    random_start = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    Start2.append(random_start.strftime("%m/%y"))
    random_end = random_start + timedelta(days=random.randint(0, (end_date - random_start).days))
    End2.append(random_end.strftime("%m/%y"))
  else:
    Start2.append("N/A")
    End2.append("N/A")
Start2 = np.array(Start2)
End2 = np.array(End2)

# assign roles to Role 3 and make sure values are nan where Role 2 is nan
Role3 = np.random.choice(role_list, 3000, replace=True)
Role3[empty_idx] = "N/A"
Role3[empty_idx2] = "N/A"
# randomly choose some roles in Role 3 to be nan
Role3_not_empty = np.where(Role3 != "N/A")[0]
empty_idx3 = np.random.choice(Role3_not_empty, size=500, replace=False)
Role3[empty_idx3] = "N/A"
# assign dates to where Role 3 is not nan
Role2_not_nan = np.where(Role3 != "N/A")[0]
Start3 = []
End3 = []
for i in range(3000):
  if i in Role2_not_nan:
    random_start = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    Start3.append(random_start.strftime("%m/%y"))
    random_end = random_start + timedelta(days=random.randint(0, (end_date - random_start).days))
    End3.append(random_end.strftime("%m/%y"))
  else:
    Start3.append("N/A")
    End3.append("N/A")
Start3 = np.array(Start3)
End3 = np.array(End3)

In [ ]:
df_rs = pd.DataFrame({'Applicant ID': Applicant_ID, 'School Name': School_Name, 'GPA': GPA, 'Degree': Degree, 'Location': Location, 'Gender': Gender, \
                   'Veteran status': Veteran_status, 'Work authorization': Work_authorization, 'Disability': Disability, 'Ethnicity': Ethnicity, \
                   'Role 1': Role1, 'Start 1': Start1, 'End 1': End1, 'Role 2': Role2, 'Start 2': Start2, 'End 2': End2, \
                   'Role 3': Role3, 'Start 3': Start3, 'End 3': End3})
df_rs.to_csv('resume_scorer_data.csv', index=False)

In [ ]:
# df_ce = pd.DataFrame({'Applicant ID': Applicant_ID, 'School Name': School_Name, 'GPA': GPA, 'Degree': Degree, 'Location': Location, 'Gender': Gender, \
#                    'Veteran status': Veteran_status, 'Work authorization': Work_authorization, 'Disability': Disability, 'Ethnicity': Ethnicity, \
#                    'Role 1': Role1, 'Start 1': Start1, 'End 1': End1, 'Role 2': Role2, 'Start 2': Start2, 'End 2': End2, \
#                    'Role 3': Role3, 'Start 3': Start3, 'End 3': End3, 'Resume score': Resume_score})
# df_ce.to_csv('candidate_evaluator_data.csv', index=False)